version: '3'

services:
  reservation:
    build: ./
    container_name: reservations
    depends_on:
      - "database"
    links:
      - "database"
    restart: always
    ports: 
      - '3002:3002'

  # results:
  #   build: results_server/
  #   depends_on:
  #     - 'database'
  #   ports:
  #     - '3000:3000'

  database:
    build: db/
    container_name: mysqlreservations
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql1passres
      # find how to pass mysql ip as environment prop